### ISSUE TITLE
Tutorial Reviews

### ISSUE THREAD

**Issue by edhager** [dojo/dojo.io#149]
Here is a partial review of the tutorials.

**All Dojo 2 tutorials**

- The Prerequisites sections needs to mention that the dojo cli has to be installed globally.  It could link to https://dojo.io/tutorials/000_local_installation/.  This is important because people may land on this page from a Google search.
- The Prerequisites sections need to tell the user to run "npm install" after unzipping the downloaded file.
- It took me a bit to figure out the balls on the left are back buttons.  It seems odd to have one UI mechanism to move forward (button) and a different one to move backwards (dots).  Plus I can move back to the very first screen with "Overview" and "Prerequisites".
- On the last pages, the next button is not displayed as expected but if I click on the grey bar where the next button was located, it takes me back to the first page (Overview) of the tutorial.  Kind of odd.
- Some tutorials have summary pages and some include the summary at the bottom of the last page.  Do we want that to be more consistent?
- The summaries at the top with the start do not all have the same punctuation.  I would make sure they all start with a capital letter and end in a period.

**tutorials/001_static_content/**

_Starting the development server_

- I ran the dojo build command, started my VirtualBox VM running Windows 10 and tried opening the app in IE11.  I get "Invalid Host header" displayed in the browser.

_Page content_

- In the "Page content" screen, some of the actions for me to take are highlighted with an arrow icon in bold. Like "Open index.html file in the src directory and remove the <p> tag and its content, "Welcome to biz-e-corp"." Some actions for me to take are normal text buried in a paragraph like "To do that, open up the HelloWorld.ts file. It is located in /src/widgets. You should see something like this:".  This needs to be more consistent.
- "create a HTML element" should be "create an HTML element"
- This text below is confusing. It says "Now, let's replace..." but then instead of telling me to do something, it says "We will build..." like if sometime later, we will work on it.  I think that needs to be rewritten to tell me "go do x-y-z and then click on show solution".
> The v function simply instructs Dojo 2 to create a HTML element, in this case a <div> element with the text “Hello, Dojo World!” inside of it. Now, let’s replace the `<div>` tag with an `<h1>` tag. We will build a view that allows the user to view Biz-E Corp’s workers, so we will add the content “Biz-E Bodies” to the document.
> 
> When you are finished, click on show solution to see the results.

- I think all of the links in the tutorials should have a target attribute so we don't lose our place in the tutorial.

_Virtual DOM properties_

- Reword "If we want to create a h1 element...".  Make is say something more like "Now we will create...".
- This doesn't say which file we are updating "Update the v function call, with a title attribute like this.".  We are on a new page in the tutorial so I wouldn't make the reader assume we are working in the same file from the previous page.
- Change "next tutorial" to the name of the tutorial: "Components of a Dojo 2 application".

**https://dojo.io/tutorials/002_creating_an_application/**

_Overview_

- Awkward "This will not be a comprehensive discussion about all of the parts that can potentially be a part of a Dojo 2 application".  How about "This will not be a comprehensive discussion about all of the possible Dojo 2 application parts.  We will focus on the basic application that we started in "Your first Dojo 2 application (this is a link)".

_The main HTML document_

- Needs help around "take leverage": "The next advantage is that Dojo 2 can take leverage third-party libraries with ease."

_The projector_

- I would replace "last" with the name of the tutorial so if someone landed here from a google search or a shared link, they know what we are talking about.
- In the following sentence, I would replace "view" with "DOM".  View is too abstract and could be used to talk about the vdom: "Whenever a Dojo 2 application needs to update the view...".

_Widgets_

- Throughout the tutorials, watch out for using the same word really close together.  "both" for example: "Widgets are the basic building blocks of Dojo 2’s user interface. They combine both the visual and behavioral aspects of a component into a single element. Both of these aspects are encapsulated within the widget’s implementation."  "Both of these aspects" could be replaced with "These".
- Two "the": "Since the the visual (HTML)...".
- Double "and": "The widget encapsulates its visual and and behavioral aspects."

_Summary_

- Change "next tutorial" to the name of the tutorial: "Creating widgets".

**https://dojo.io/tutorials/003_creating_widgets/**

_Creating the application widget_

- Replace "In the first tutorial in this series, we created..." with "In 'Your first Dojo 2 application', we created...".
- In "expand our application to show each worker’s portrait", "each" is a pronoun that in this case has nothing to refer back to.  

_Creating the Worker widget_

- Make sure the highlighted instructions, the ones with the arrows, have consisten capitalizations.  This one does not start with a capital letter:  "run the application with dojo build --watch and navigate to http://localhost:9999".

_Configuring a widget_

- The start of this page seems odd because we have 3 more steps to go in the tutorial: "The final step in creating this widget is to update".  Could we say someting like "To finish the widget's functionality|behaviour|something we will update the render method...".
- The fully justified text formatting in the "Remember" box looks funny on the "and navigating to" line.  Too much space.

_Styling widgets with CSS modules_

- Is a blank line missing.  Strange whitespace or lack of whitespace after the first sentence.
- Awkward sentence: "This obfuscation is done by the dojo build command’s use of CSS Modules when it compiles the project to ensure that CSS selectors are localized to a given widget."
- In the last paragraph, what is the remaining task? "We’ve almost achieved our goal of displaying a collection of Biz-E Bodies, but we have one task remaining."  The next sentence seems to dive into a suggested solution to the unknown task.

_Moving the Worker into a container_

- I think we need a sentence in the beginning that describes the purpose of the WorkerContainer class.  Why are we creating it?
- In "we have added an key", "an" needs to be "a".

_Summary_

- Replace "next tutorial" with "Responding to events".  This gives the user a better idea where they are in the tutorials in case they need to navigate to where they left off.

**Comment by maier49** [comment]
The following issues that @edhager pointed out are simple grammatical errors or typos that shouldn't need any type of editorial review, and are addressed in #156 :

>Needs help around "take leverage": "The next advantage is that Dojo 2 can take leverage third-party libraries with ease."
> Two "the": "Since the the visual (HTML)...".
> Double "and": "The widget encapsulates its visual and and behavioral aspects."
>In "we have added an key", "an" needs to be "a".


My review of the contents, I tried to avoid repeating anything that Ed had already pointed out:

General Comments:
* We need more tests, right now only one widget has any unit tests.
* Should consider using routing to allow browser navigation between sections in a tutorial, or at least updating the UI with a clear way to get back to the intro page where the template can be downloaded.
* When importing a new css file, compilation will fail, and the dts file will not be generated until the importing widget is actually included in a render function. I'm assuming this has something to do with tree shaking but have not investigated it at all. This isn't intuitive and could result in somebody trying to debug an issue that doesn't really exist if they realize that compilation is failing before they make all the changes needed for it to work. If this behavior isn't something that can or should be changed in `cli-build` it may make sense to change the order of edits so that this situation is avoided.
* Sequential updates to the same method usually just show the entire code of the method again. If possible we should also highlight the parts that have changed.

Tutorial 2 - Creating an Application:

* From the tutorial:
>In this example, the widget is simple enough that the function always returns the same result. We could make this widget more sophisticated by giving it some internal state that can be used to alter how the DNodes are generated without having to change how the rest of the application interacts with it. This encourages the development of loosely coupled components that are easier to develop and maintain over time. 

This seems to be implying that adding internal state is a good pattern that should be encouraged, but I thought we were trying to minimize the internal state of widgets. If "this" is not referring to the practice of adding internal state then we should be more specific.

* This tutorial doesn't include a link to the finished code

Tutorial 3- Creating an Application:

* From the tutorial:
>To start, let's use the simplest render method by adding this to the App class:

This phrasing seems a little strange. It brings up unnecessary philosophical questions.
Is `v('div')` simpler than `v('p')`? Are these both "the simplest render method"?
Something like "let's use a simple render method" or "let's start with a simple render method" sounds better to me. 

* From the tutorial:
>...we are going to need two children. One `<img>` tag to show the worker's portrait and a `<strong>` tag to display the worker's name.
Try and implement that using the URL images/worker.svg and print the first and last names.

When I read this I first thought: but we have no properties so there's no way we know the name to render here. I shortly realized, and you can certainly infer from the context, that
we're just going to put some static text in here for now, but maybe it would be better to be explicit state what we should put in the `<strong>` tag so people don't make the same
mistake. 

* `this.classes` is used in the code without explaining why or what it does.

* We don't show changing the `Worker` import to import `WorkerContainer`, only swapping them out in the render function.

Tutorial 4 - User Interactions

* From the tutorial:
>The use of a field to store this kind of data is standard practice in Dojo 2. Properties are used to allow other components to view and modify a widget’s published state. For internal state, however, private fields are used to allow widget to encapsulate state information that should not be exposed publicly.

This may just be confusion on my part, but I thought we were trying to minimize the use of state. Obviously state needs to exist somewhere, but this seems like a more enthusiastic
endorsement than I would expect.

* The solution in the _Final Steps_ section needs a line break after "via"(or a style update). Right now you have to scroll to the right to see the full sentence.

Tutorial 5 - Form Widgets

* We do provide a demo project to get started that includes `@dojo/widgets` as a dependency, but if you've been building on the original application as you proceed through the tutorials
this dependency is missing. We should probably either include it in all of the tutorials or at least make a note of that.	

* From the tutorial:
>As mentioned before, a key is necessary whenever the same type of widget or virtual DOM element will be rendered by a widget.

This might be clearer if it said something like: 
> As mentioned before, a key is necessary whenever more than one of the same type of widget...

* From the tutorial:
>As parts of a reactive framework, Dojo 2 widgets do not normally update their own state. Rather, they inform their parent that a change has occurred via events or some other mechanism. The parent will then pass updated properties back into the widget after all of the changes have been processed. This allows Dojo 2 applications to centralize data and keep the entire application synchronized.

This sounds more like what I understand the encouraged pattern to be, compared to the previous discussions about state. The juxtoposition could leave someone feeling unclear on what is expected and encouraged.

* At the end of the tutorial it says
>First test the happy path 
but then we never test any unhappy paths.

* This tutorial doesn't include a download link

**Comment by dylans** [comment]
Feedback all seems reasonable @maier49 and @edhager ... I'd say proceed... definitely the UI of the multi-part tutorial must improve (both screen space used, UI, navigation, and bookmarkability).

**Comment by edhager** [comment]
Here is feedback for the last three tutorials:

https://dojo.io/tutorials/004_user_interactions/

- As with the other tutorials, replace "previous tutorial" with the name of the tutorial.  
- When it talks about why we can't use anonymous functions for event listeners, we should give maquette's output when that happens so people recognize the error as text.  It may result in some Google traffic.
- "Now that we have an event handler it is time to extend the" needs a comma.  In that sentence, remove "to be able'
- The comma is not needed in this: "We also need to update the CSS selector for the front view, by changing the selector"
- The dash seems odd in this "viewing the application in a browser - all three cards".  I would use a period and start a new sentence.
- Last screen "Be aware that the value of an event handler cannot change once the widget has been rendered".  The "value of an event handler" is weird. It is really the property's value that cannot change.
- Change "next tutorial" to the name of the tutorial.

https://dojo.io/tutorials/005_form_widgets/

- As with the other tutorials, replace "previous tutorial" with the name of the tutorial.  Also "last tutorial" links.
- Question... If we have the "private" access modifier, should we continue to add the underscore to the method name?
- Change "next tutorial" to the name of the tutorial.

https://dojo.io/tutorials/006_deploying_to_production/

- As with the other tutorials, replace "previous tutorial" with the name of the tutorial.  
- The "Recommendation" box is redundant.  The "Prerequisites" in each tutorial intro page says to download the code.  Should all of those "Prerequisites" be modified to say "to get the most value..."?
- " so that the application and its styling rules will be available." Remove "that".
- The section mentioning "--element" and "--elementPrefix" needs a learn-more-about-it link.

**Comment by maier49** [comment]
These issues still have not been addressed:
* Question... If we have the "private" access modifier, should we continue to add the underscore to the method name?
* Sequential updates to the same method usually just show the entire code of the method again. If possible we should also highlight the parts that have changed
* I think all of the links in the tutorials should have a target attribute so we don't lose our place in the tutorial.

**Comment by edhager** [comment]
For @maier49's remaining issues:

>Question... If we have the "private" access modifier, should we continue to add the underscore to the method name?

It was decided to leave the underscores.  While there is little benefit in the TypeScript code, they are still useful for people using the generated JavaScript code.

>Sequential updates to the same method usually just show the entire code of the method again. If possible we should also highlight the parts that have changed

Ticket #189 was created to track this issue.

>I think all of the links in the tutorials should have a target attribute so we don't lose our place in the tutorial.

Ticket #190 was created to track this issue.
