### ISSUE TITLE
Create "Internationalization" article

### ISSUE THREAD

**Issue by eheasley** [dojo/dojo.io#18]

**Comment by morrinene** [comment]
@mwistrand 

Provide the following so an article can be drafted that provides more detailed background information about key features of Internationalization and key concepts and patterns for being effective in working with it in Dojo 2:

- Summary of key points that a user should know about the topic
- Code examples (or links to relevant existing examples)
- Links to relevant reference material

**Comment by mwistrand** [comment]
I hope the following suffices. The information provided on date/time/number/unit formatting is bare-bones, but there really aren't too many considerations for them beyond the plethora of options.

---

## General Outline

- Overview
- Reading and setting the current locale
- Loading CLDR data
- Locale-specific messages (with or without CLDR data)
- Date/Time formatting
- Unit formatting
- Number formatting
- Internationalization with `@dojo/widget-core`
- The build process

## Expanded Outline

### Overview

- `@dojo/i18n` provides everything that is needed to internationalize and localize an application, from locale-specific messaging to date, number, and unit formatting.
- Dojo 2 applications also rely on `@dojo/cli-build` and `@dojo/widget-core` to simplify internationalization within the Dojo 2 ecosystem.
- Most functionality requires [CLDR data](https://github.com/unicode-cldr/). However, no CLDR data are included by Dojo 2, both due to the size of the complete CLDR data and to prevent tying applications to a specific version of the CLDR data.
- The `@dojo/i18n` README lists which CLDR data are required by which portions of the i18n ecosystem.
- There are two types of formatters: formatters that accept both the value to format and any relevant options, and functions that accept options that return formatters that are specific to those options. As a general rule, it is considered best practice to use the latter when the same options need to be used to format values more than once.
- All methods are exported by `@dojo/i18n/main`, but often an application will not need the entire i18n ecosystem, so it is best to import directly from individual modules.

### Reading/Setting the locale

- All functionality for reading/setting the locale is exposed by `@dojo/i18n/i18n`.
- The `systemLocale` property represents the user's system locale.
- The `locale` property of the default export contains the application's current locale. This is changed with the `switchLocale` method, and defaults to the `systemLocale`.
- The `switchLocale` method accepts a string locale, changes the `locale` property of the default export, and notifies any observers registered with `observeLocale`.
- The `observeLocale` method can be used to observe changes to the application locale. It accepts an [Observable](https://github.com/tc39/proposal-observable) whose `next` method is passed the new locale.

```typescript
// reading and setting the locale
import i18n, { switchLocale, systemLocale } from '@dojo/i18n/i18n';

console.log(i18n.locale === systemLocale); // true
switchLocale('ja');
console.log(i18n.locale); // 'ja'
```

```typescript
// observing locale changes
import { observeLocale, switchLocale } from '@dojo/i18n/i18n';

// Create a subscription that updates the <html> tag's "lang" attribute when
// the locale is changed.
const subscription = observeLocale({
	next: (locale: string) => {
		document.documentElement.setAttribute('lang', locale);
	}
});

switchLocale('es');

// destroy the observer when we no longer need to observe locale changes
subscription.unsubscribe();
```

### Loading CLDR Data

- All CLDR data that might be needed by an application can be found in the [Unicode JSON ](https://github.com/unicode-cldr) GitHub repos.
- The list of CLDR data required by each portion of the ecosystem can be found in the [README](https://github.com/dojo/i18n).
- CLDR data must be registered with the i18n ecosystem via `@dojo/i18n/cldr/load` (the default export) before the corresponding formatters can be used.
- The default export from `@dojo/i18n/cldr/load` is a function that can either accept a JSON object of CLDR data, or an array of paths to JSON files that should be loaded.
- `@dojo/i18n/cldr/load` also exposes an `isLoaded` function that can be used to determine whether specific data have been loaded.

**Example: Loading CLDR Data**

```typescript
import loadCldrData, { isLoaded } from '@dojo/i18n/cldr/load';

console.log(isLoaded('supplemental', 'likelySubtags')); // false
console.log(isLoaded('supplemental', 'plurals-type-cardinal')); // false

loadCldrData([
  './path/to/cldr/supplemental/likelySubtags.json',
  './path/to/cldr/supplemental/plurals.json'
]).then(() => {
  console.log(isLoaded('supplemental', 'likelySubtags')); // true
  // Notice that the check is for the property on the JSON object, not the JSON filename.
  console.log(isLoaded('supplemental', 'plurals-type-cardinal')); // true
});
```

### Locale-specific Messages

**Overview**

- Message loading and formatting is provided by `@dojo/i18n/i18n`.
- The default export accepts a bundle (see below) and an optional locale, and returns a promise to the loaded messages.
- If a locale is not provided, the root application locale is assumed.

**Bundle Format**

- As in Dojo 1, messages in Dojo 2 are separated into default bundles that contain defaults for all messages used by an application, as well as any additional locale-specific bundles.
- Default bundles must expose a `default` export, which must be an object, and which must contain the following:
  - A string `bundlePath` representing the location of the default bundle. For example, if the default bundle is located at `src/nls/main.ts`, then the bundle path would be `src/nls/main`. This is used to resolve the location of locale-specific messages (see below).
  - An optional `locales` array containing all locales supported by the bundle.
  - A `messages` object containing key-value pairs of default messages.
- Locale-specific bundles must be located under directories within the same directory as their default bundle. For example, if the `locales` array exposed by a bundle located at `src/nls/main` is specified as `[ 'fr', 'fr-CA' ]`, then the messages for those two locales must be located at `src/nls/fr/main` and `src/nls/fr-ca/main`, respectively.
- Locale-specific bundles must expose a `default` export, and this export must be an object containing the locale-specific messages.
- Locale-specific bundles need not contain all possible messages; any missing messages will be filled in by the default bundle. For example, if the default bundle contains the messages `{ foo: 'bar', baz: 'bat' }`, but a locale-specific bundle contains only `{ baz: 'xyzzy' }`, then the default value for `foo` ("bar") will be used.

**Locale Resolution**

- Locales are resolved from most-specific to least specific. If, for example, the locale is specified as `'ar-JO'` (Jordanian Arabic), then a bundle's `locales` array will be used to determine whether there are messages specific to `'ar-JO'`. If so, then those messages will be loaded. If not, then the next appropriate locale will be used (in this case, `'ar'`). If no relevant locale is supported, then the default messages are returned.

**Example: Supported Locale**

```typescript
// Default bundle: "src/nls/greetings.ts"
const bundlePath = 'src/nls/greetings';
const locales = [ 'ar', 'ar-JO' ];
const messages = {
  hello: 'Hello',
  helloReply: 'Hello',
  goodbye: 'Goodbye'
};
export default { bundlePath, locales, messages };
```

```typescript
// "src/nls/ar/greetings.ts"
const messages = {
	hello: 'السلام عليكم',
	helloReply: 'و عليكم السام',
	goodbye: 'مع السلامة'
};
export default messages;
```

```typescript
// "src/nls/ar-JO/greetings.ts"
const messages = {
	hello: 'مرحبا',
	helloReply: 'مرحبتين'
};
export default messages;
```

```typescript
// loading messages for `ar-JO`
import i18n, { Messages } from '@dojo/i18n/i18n';
import greetings from './nls/greetings';

i18n(greetings, 'ar-JO').then((messages: Messages) => {
  console.log(messages.hello); // 'مرحبا'
  console.log(messages.helloReply); // 'مرحبتين'
  
  // Since src/nls/ar-JO/greetings.ts does not specify a "goodbye" message,
  // the next best-supported value is used. In this case, the value from
  // src/nls/ar/greetings.ts is used.
  console.log(messages.goodbye); // 'مع السلامة'
});
```

**Example: Unsupported Locale**

```typescript
// Attempt to load messages for "fr", which is not in the `locales` array
import i18n, { Messages } from '@dojo/i18n/i18n';
import greetings from './nls/greetings';

i18n(greetings, 'fr').then((messages: Messages) => {
  // The default messages are returned
  console.log(messages.hello); // 'Hello'
  console.log(messages.helloReply); // 'Hello'
  console.log(messages.goodbye); // 'Goodbye'
});
```

### Message Formatting

- `@dojo/i18n/i18n` provides two different forms of formatting: simple variable replacement, and the more robust ICU message format.
- If CLDR data required by the ICU message format capabilities are not loaded, then simple variable replacement is used.
- There are two methods used to format messages: `formatMessage`, which can be used to format a message immediately, and `getMessageFormatter`, which returns a function that can be used to format the same message string multiple times with different options.

**Example: Basic Variable Replacement**

```typescript
// src/nls/greetings.ts
const bundlePath = 'src/nls/greetings';
const messages = {
  hello: 'Hello, {name}!'
};
export default { bundlePath, messages };
```

```typescript
import i18n, { getMessageFormatter, formatMessage } from '@dojo/i18n/i18n';
import greetings from './nls/greetings';

// First, register the bundle with `@dojo/i18n`
i18n(greetings).then(() => {
  const formatted = formatMessage(greetings, 'hello', { name: 'Margaret Mead' });
  console.log(formatted); // "Hello, Margaret Mead!"
  
  const formatter = getMessageFormatter(greetings, 'hello');
  console.log(formatter({ name: 'Marshall Sahlins' })); // "Hello, Marshall Sahlins!"
});
```

**Example: ICU Message Format**

```typescript
// src/nls/greetings.ts
const bundlePath = 'src/nls/greetings';
const messages = {
  hello: `{personCount, plural, offset:1
    =0: {Hello, nobody!},
    =1: {Hello, {name}!},
    other {Hello, everyone!}}`
};
export default { bundlePath, messages };
```

```typescript
import loadCldrData from '@dojo/i18n/cldr';
import i18n, { getMessageFormatter } from '@dojo/i18n/i18n';
import greetings from './nls/greetings';

// First, ensure the appropriate CLDR data have been loaded
loadCldrData([
  './nls/cldr/supplemental/likelySubtags.json',
  './nls/cldr/supplemental/plurals.json'
]).then(() => {
  // Next, register the bundle with `@dojo/i18n`
  return i18n(greetings);
}).then(() => {
  const formatter = getMessageFormatter(greetings, 'hello');
  
  // "Hello, nobody!"
  console.log(formatter({ personCount: 0 }));
  
  // "Hello, Bill Evans!"
  console.log(formatter({
    name: 'Bill Evans',
    personCount: 1
  }));
  
  // "Hello, everyone!"
  console.log(formatter({ personCount: Infinity }));
});

i18n(greetings).then(() => {
  const formatted = formatMessage(greetings, 'hello', { name: 'Margaret Mead' });
  console.log(formatted); // "Hello, Margaret Mead!"
  
  const formatter = getMessageFormatter(greetings, 'hello');
  console.log(formatter({ name: 'Marshall Sahlins' })); // "Hello, Marshall Sahlins!"
});
```

### Date/Time Formatting

- `@dojo/i18n/date` exposes the following methods:
  - `formatDate`: formats a date based on provided options
  - `formatRelativeTime`: returns a formatted string representing a relative time value
  - `getDateFormatter`: returns a function that formats a date
  - `getDateParser`: returns a function that parses a date string
  - `getRelativeTimeFormatter`: returns a function that formats a relative time
  - `parseDate`: parses a date string into a `Date` object
- Requires CLDR data (see the README)

**Date Options**

The `formatDate`, `getDateFormatter`, `getDateParser`, and `parseDate` methods accept the following `options`:

| Option | Description |
| ------ | ----------- |
| `date` | One of the following strings: "full", "long", "medium", or "short" |
| `time` | One of the following strings: "full", "long", "medium", or "short" |
| `datetime` | One of the following strings: "full", "long", "medium", or "short" |
| `skeleton` | A string comprised of valid [date field symbols](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) (e.g., "yMMMd" => "May 24, 2017"). This is useful for specifying exact formats when one of the existing shorthands ("full", "long", "medium", "short") is insufficient. |

Shorthand examples:

| Option | Output |
| ------ | ------ |
| `{ date: 'short' }` | '4/1/2017' |
| `{ date: 'medium' }` | 'Apr 1, 2017' |
| `{ date: 'long' }` | 'April 1, 2017' |
| `{ date: 'full' }` | 'Saturday, April 1, 2017' |
| `{ time: 'short' }` | '3:56 AM' |
| `{ time: 'medium' }` | '3:56:42 AM' |
| `{ time: 'long' }` | '3:56:42 AM GMT-5' |
| `{ time: 'full' }` | '3:56:42 AM GMT-05:00' |
| `{ datetime: 'full' }` | "Saturday, April 1, 2017 at 3:56:42 AM GMT-05:00" |
| `{ datetime: 'long' }` | "April 1, 2017 at 3:56:42 AM GMT-5" |
| `{ datetime: 'medium' }` | "Apr 1, 2017, 3:56:42 AM" |
| `{ datetime: 'short' }` | "4/1/17, 3:56 AM" |

The `getRelativeTimeFormatter` and `formatRelativeTime` methods accept the following `options`:

| Option | Description |
| ------ | ----------- |
| `form` | "short" or "narrow"; when not provided, defaults to long form |

`form` option examples using `formatRelativeTime(3, 'week', 'fr')` ("in three weeks" in French):

| Option | Output |
| ------ | ------ |
| undefined | 'dans 3 semaines' |
| `{ form: 'short' }` | 'dan 3 sem.' |
| `{ form: 'narrow' }` | '+3 sem.' |

**Example**

```typescript
// Assuming all appropriate CLDR data have been loaded for French date formatting...
import { switchLocale } from '@dojo/i18n';
import { formatDate, parseDate, formatRelativeTime } from '@dojo/i18n/date';

switchLocale('fr');

const date = new Date(2017, 3, 1);
formatDate(date, { date: 'full' }, 'fr'); // samedi, 1 avril 2017
parseDate('samedi, 1 avril 2017', { date: 'full' }); // Date(2017, 3, 1)
formatRelativeTime(-1, 'week'); // la semaine dernière
```

### Number and Unit Formatting

- `@dojo/i18n/number` exposes the following methods:
  - `formatCurrency`: formats a number as a currency
  - `formatNumber`: formats a number according to the specified options
  - `getCurrencyFormatter`: returns a function that formats a number as a currency
  - `getNumberFormatter`: returns a function that formats a number according to specified options
  - `getNumberParser`: returns a function that parses a number from a locale string
  - `getPluralGenerator`: returns a function that returns the plural group for a specified number: "zero", "one", "two", "few", "many", or "other"
  - `parseNumber`: parses a number from a locale string
  - `pluralize`: returns the plural group for a specified number: "zero", "one", "two", "few", "many", or "other"
- `@dojo/i18n/unit` exposes the following methods:
  - `formatUnit`: formats a number for a specific unit
  - `getUnitFormatter`: returns a function that formats a number for a specific unit

`formatNumber`, `getNumberFormatter`, `parseNumber`, and `getNumberParser` accept the following `options`:

| Option | Description |
| ------ | ----------- |
| `style` | "decimal" or "percent". Defaults to "decimal" |
| `minimumIntegerDigits` | Optional. The minimum number of whole integers that must be present in the formatted string. Leading zeros are added as necessary. |
| `minimumFractionDigits` | Optional. The minimum number of fraction digits that must be present in the formatted string. Trailing zeros are added as needed. |
| `maximumFractionDigits` | Optional. The maximum number of fraction digits that cam be present in the formatted string. The number is rounded using `Math.round` unless the `round` option is specified (see below). |
| `minimumSignificantDigits` | Optional, but if used a `maximumSignificantDigits` value must be included. The minimum number of signicant digits that must be present in the formatted string. Trailing, fractional zeros are added as needed. |
| `maximumSignificantDigits` | Optional, but if used a `minimumSignificantDigits` value must be included. The maximum number of signicant digits that can be present in the formatted string. Numbers are rounded to the nearest significant digit as required. |
| `round` | "ceil", "floor", or "truncate". Defaults the `Math.round` implementation. |
| `useGrouping` | If true (the default), the group separator is used |

Number format option examples (using `9.27` unless otherwise specified):

| Option | Output |
| ------ | ------ |
| `{ style: 'decimal' }` | '9.27' |
| `{ style: 'percent' }` | '9.27%' |
| `{ minimumIntegerDigits: 5 }` | '00009.27' |
| `{ minimumFractionDigits: 3 }` | '9.270' |
| `{ maximumFractionDigits: 1 }` | '9.3' |
| `{ minimumSignificantDigits: 4, maximumSignificantDigits: 4 }` | '9.270' |
| `{ round: 'floor', maximumDecimalDigits: 1 }` | '9.2' |
| `{ round: 'ceil', maximumDecimalDigits: 1 }` | '9.3' |
| `{ useGrouping: true }` | For `1000`: '1,000' |

`formatCurrency` and `getCurrencyFormatter` also use the number formatting options, but accept a different `style` option:

| Option | Description |
| ------ | ----------- |
| `style` | "accounting", "code", or "name". Defaults to "accounting" |

Currency style examples (`formatCurrency('9.27', 'USD')`):

| Option | Output |
| ------ | ------ |
| `accounting` | '$9.27' |
| `code` | '9.27 USD' |
| `name` | '9.27 US dollars |

**Example: Number Formatting**

```typescript
// Assuming all relevant CLDR data have been loaded
import { switchLocale } from '@dojo/i18n/i18n';
import { formatNumber, parseNumber } from '@dojo/i18n/number';

// "12.4"
formatNumber(12.33, {
	maximumFractionDigits: 1,
	round: 'ceil'
});

// "12.3"
formatNumber(12.33, {
	maximumFractionDigits: 1,
	round: 'floor'
});

formatNumber(1234567.89); // "1,234,567.89"
formatNumber(1234567.89, { useGrouping: false }); // "1234567.89"

// Change the locale to German
switchLocale('de');

const formatted = formatNumber(1234567.89); // "1.234.567,89"
parseNumber('25 %', { style: 'percent' }); // 0.25
```

**Example: Currency Formatting**

```typescript
// Assuming all relevant CLDR data have been loaded
import { switchLocale } from '@dojo/i18n/i18n';
import { formatCurrency } from '@dojo/i18n/number';

formatCurrency(71592.37, 'USD'); // "$71,592.37"
formatCurrency(71592.37, 'USD', { style: 'code' }); // "71,592.37 USD"

// Switch the locale to French
switchLocale('fr');

formatCurrency(71592.37, 'EUR'); // "71 592.37 €"
formatCurrency(71592.37, 'EUR', { style: 'code' }); // "71 592,37 EUR"
```

**Example: Plural Formatting**

Different languages have different rules for how words should be pluraized. For example, in English, "0" is essentially treated as a plural, whereas in other languages it is treated as a singular value. Other languages are more complex, which might pluralize "2" items uniquely from how 3+ items are pluralized.

```typescript
// Assuming all relevant CLDR data have been loaded
import { switchLocale } from '@dojo/i18n/i18n';
import { pluralize } form '@dojo/i18n/pluralize';

pluralize(0); // other
pluralize(1); // one
pluralize(2); // other
pluralize(3); // other
pluralize(10); // other
pluralize(11); // other

// Change the locale to Arabic
switchLocale('ar');

pluralize(0); // zero
pluralize(1); // one
pluralize(2); // two
pluralize(3); // few
pluralize(10); // few
pluralize(11); // many
```

**Example: Unit Formatting**

```typescript
// Assuming all relevant CLDR data have been loaded
import { formatUnit } from '@dojo/i18n/unit';

formatUnit(1, 'foot'); // '1 foot'
formatUnit(5280, 'foot'); // '5,280 feet'
formatUnit(1, 'foot', { form: 'long' }); // '1 foot'
formatUnit(5280, 'foot', { form: 'long' }); // '5,280 feet'
formatUnit(1, 'foot', { form: 'short' }); // '1 ft'
formatUnit(5280, 'foot', { form: 'short' }); // '5,280 ft'
formatUnit(1, 'foot', { form: 'narrow' }); // '1′'
formatUnit(5280, 'foot', { form: 'narrow' }); // '5,280′'
```

### Localizing widgets

- Since Dojo 2 widgets render to a projector, `lang` and `dir` attributes are _not_ added to the `<html>` tag. It is up to app developers to update these attributes as necessary.
- `@dojo/i18n` is designed to be an independent package, so `@dojo/widget-core` provides a custom mixin to make working with it more friendly.
- Widgets assume the current locale (`i18n.locale`) unless `properties.locale` is set. If, for example, the current locale is English, then the available English messages will be used for all widgets.
- Since Dojo 2 widgets are controlled, child widgets do not automatically inherit the locale from the parent. Parents must pass the correct locale as needed to child widgets.
- Text direction defaults to left-to-right, but can be changed by setting `properties.rtl` to true.
- Bundles are localized by passing them to the `localizeBundle` method. If messages have not been loaded yet, then the default messages are returned, and the widget is invalidated once the locale-specific messages have loaded.
- The object returned by the `localizeBundle` method contains all the messages, as well as a `format` method that takes a message key as well as any options. If message formatting is not required, then messages can be directly accessed (e.g., `messages.hello`).

```typescript
import I18nMixin, { I18nProperties } from '@dojo/widget-core/mixins/I18n';
import greetings from './nls/greetings';

export interface GreetingProperties extends I18nProperties {
   name: string;
}

const GreetingBase = I18nMixin(WidgetBase);
export default class Greeting extends GreetingBase<GreetingProperties> {
  render() {
    const messages = this.localizeBundle(greetings);
    const { name } = this.properties;
    const hello = messages.format('hello', { name });
    
    return v('p', [ hello ]);
  }
}
```

### i18n and the build process

- Dojo 2 uses webpack to build applications, but since webpack is a bundler and not a loader, a few extra steps are required to ensure that CLDR data and locale-specific messages are included in the built application.
- Currently, Dojo 2 does not ensure that the application locale is one of the supported locales. This will change in a future release, but in the meantime, the initial locale must be manually set in the application with `switchLocale`.
- CLDR data are parsed from calls to `@dojo/i18n/cldr/load`.
- A `.dojorc` can (and should be) used to set i18n-specific settings. All i18n settings need to go under the `build-webpack` namespace:
  - `locale`: the default locale for the application
  - `supportedLocales`: an optional array of additional locales to include in the build
  - `messageBundles`: an optional array of any message bundles to include in the build.
  
**Example**

Suppose that the default locale is English, but Spanish and French are also supported:

```
// .dojorc
{
  "build-webpack": {
    "locale": "en",
    "supportedLocales": [ "es", "fr" ],
    "messageBundles": [ "src/nls/main" ]
  }
}
```

```typescript
import loadCldrData from '@dojo/i18n/cldr/load';
import i18n, { switchLocale } from '@dojo/i18n/i18n';

// Eventually this will be handled automatically, but for now this is required
const defaultLocale = 'en';
const supportedLocales = [ 'en', 'fr', 'es' ];
const rootLocale = i18n.locale.split('-')[0];
const isLocaleSupported = supportedLocales.some(locale => locale === rootLocale);

if (!isLocaleSupported) {
  switchLocale(defaultLocale);
}

// The build will parse out these URLs, load them, and include the data in the build
export default loadCldrData([
  './cldr/supplemental/likelySubtags.json',
  './cldr/supplemental/plurals.json'
]);
```
