### ISSUE TITLE
Create 6th tutorial: "Deploying to Production"

### ISSUE THREAD

**Issue by eheasley** [dojo/dojo.io#19]
This tutorial will walk the learner through the compilation and deployment of a Dojo 2 application to production

**Comment by morrinene** [comment]
Adding @agubler to outline key points and examples for the drafting of this tutorial

**Comment by morrinene** [comment]
@mwistrand 

Outline the following items for the creation of this tutorial:

- Summary of key points about what we are teaching in this tutorial
- Takeaways from the Tutorial
- High-level outline of steps for Tutorial
- Initial and final version of the code
- Code examples (or links to relevant existing examples)
- Links to any relevant reference material

**Comment by mwistrand** [comment]
@vansimke At this point the build process is relatively simple, so please let me know if what is listed below requires more information:

**Key Points**

- Dojo 2 uses the `@dojo/cli-build-webpack` package to compile applications with webpack.
- A Dojo 2 application is self-contained and built to the `dist` directory.
- When creating a new application with the `dojo create` command, all build tools are included automatically, so there is no need to install additional packages.
- The build process requires a small number of options, which can be executed as command line flags or included in a `.dojorc`.

**Outline**

1. Create a new app.
2. Demonstrate `$ dojo build` (outputs app to `dist`).
3. Add nls messages.
4. Run `$ dojo build --locale=en --messageBundles=src/nls/main`.
5. Add a `.dojorc`. Note: each `cli-` package has its own namespace within the `.dojorc`, so all config options for the build are under a `"cli-build"` object (see below).

**Relevant Code**

Step 3 ("Add nls messages"):

```typescript
// src/nls/main.ts
const bundlePath = 'src/nls/main';
const messages = {
  greeting: 'Hello, Dojo World!'
};
export default { bundlePath, messages };
```

```typescript
// src/widgets/HelloWorld.ts
import { v } from '@dojo/widget-core/d';
import { DNode } from '@dojo/widget-core/interfaces';
import { I18nMixin, I18nProperties } from '@dojo/widget-core/mixins/I18n';
import { ThemeableMixin, theme } from '@dojo/widget-core/mixins/Themeable';
import { WidgetBase } from '@dojo/widget-core/WidgetBase';
import appBundle from '../nls/main';

import * as css from './styles/HelloWorld.m.css';

export interface HelloWorldProperties extends I18nProperties {
	stranger: boolean;
	toggleStranger: Function;
}

export const HelloWorldBase = I18nMixin(ThemeableMixin(WidgetBase));

@theme(css)
export default class HelloWorld extends HelloWorldBase<HelloWorldProperties> {

	private onClick(): void {
		this.properties.toggleStranger && this.properties.toggleStranger();
	}

	protected render(): DNode {
		const messages = this.localizeBundle(appBundle);
		const classes = this.classes(
			css.hello,
			this.properties.stranger ? css.upsidedown : null
		);

		return v('div', { classes, onclick: this.onClick }, [ messages.hello ]);
	}
}
```

Step 5 ("Add `.dojorc`"):

```
{
  "build-webpack": {
    "locale": "en",
    "messageBundles: [ "src/nls/main" ]
  }
}
```

**Comment by vansimke** [comment]
@mwistrand Just a couple of questions:

- Is there currently anyway to pass configuration information to webpack (e.g. include / exclude source maps, ...)
- how can I learn more about the options that can be provided in the `.dojorc` file for each package

**Comment by mwistrand** [comment]
Sorry for the delay, @vansimke.

`@dojo/cli-build` encapsulates the build as much as possible, so users cannot pass additional configuration options directly to webpack. If `$ dojo build` by itself does not provide what the user needs, then they can run `$ dojo eject`, which will output the webpack configuration for direct modification. But at that point, users can no longer run `$ dojo build`, and they must maintain the entire build process themselves.

As for the `.dojorc` settings for other `cli-` packages, documentation is currently sparse. In theory, however, any flag that can be specified in the command line should also be valid as a `.dojorc` setting. Each package has its own namespace within the `.dojorc`, so flags specific to `cli-build-webpack` are under `build-webpack`, and those specific to `cli-test-intern` would be under `test-intern`. For example,

```
// .dojorc
{
    "build-webpack": {
        "locale": "en"
    },
    "test-intern": {
        "all": true
    }
}
```

That said, since this tutorial concerns building for production, perhaps the additional information about `.dojorc` configuration for other packages is not needed?
