### ISSUE TITLE
Tutorial 003 - Provide in on non-optionality of properties

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#223]
Step 1: "Both of these properties are optional, so we can pass an empty object for now" (in reference to `w(Banner, {})`).

But would be good to clarify on whether the object literal is optional. When I tried it out, TypeScript complained. I feel it shouldn’t be necessary to pass an empty object even it has no properties?

Link: https://dojo.io/tutorials/003_creating_widgets/#1

**Comment by kitsonk** [comment]
This is intentional, mostly to help people not make mistakes when authoring.  @agubler can provide more context as to why.  We should provide a side note in the tutorial though.

**Comment by agubler** [comment]
Ah now I have to actually remember! 

It is due to the fact that if `properties` are allowed to be optional lose the `properties` type guarding for widgets when using `w`. As the `children` are optional it means to enable this behaviour the `properties` have to be defaulted and as it is effectively a generic it has to be cast to meaning that it allows `{}` to be passed for the _any_ widget even if it has mandatory properties. I hope that helps.

Perhaps we should put an aside that mentions the properties being mandatory is intentional to ensure the correct type guarding for all widgets
