### ISSUE TITLE
Tutorial feedback - Data-driven widgets

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#233]
https://dojo.io/tutorials/1060_data_driven_widgets/#3

Step 4: “Pass a subset of worker data into the List based on its value in Banner.ts:”

There is this line of code:

```ts
const match = name.toLowerCase().match(new RegExp(`^${value.toLowerCase()}`));
```

JavaScript has a built in `String.startsWith()` method which I feel would be better to use here.

![image](https://user-images.githubusercontent.com/381495/31778865-a372f238-b4e9-11e7-9358-4c6d4becd8c0.png)

**Comment by kitsonk** [comment]
`String.startsWith()` is ES6.  From a Dojo 2 perspective, we don't use global polyfills when we can avoid it (we can't with `Promise` and `Symbol`), we have functional ponyfills.  So for this to work it would need to look more like this.

```ts
import { startsWith } from '@dojo/shim/string';

const match = startsWith(name.toLowerCase(), value.toLowerCase());
```

**Comment by umaar** [comment]
Browser support for that method is good though:

![image](https://user-images.githubusercontent.com/381495/31817529-4c338048-b58c-11e7-8698-f6736efd7bd2.png)

It feels a shame that a tutorial couldn't use a modern web platform feature just because of IE.

On a related note, when I run `dojo build` in the terminal, I see this message:

```
webpack: Compiled successfully.
webpack: Compiling...

Dynamic features: es6-map, es6-symbol, es6-promise, es6-weakmap, es6-array, es6-array-fill, es7-array, es6-object, es2017-object, host-node, dom-mutationobserver, host-browser, postmessage, setimmediate, microtasks, raf, es6-string, es6-string-raw, es2017-string
```

Two things:

1. Are we sure `es6-string` doesn't somehow polyfill `startsWith` automatically?
2. As a general piece of feedback here, as a user, it's confusing what this message is, e.g. What is `Dynamic features`? Why is it telling me this? I think @matt-gadd mentioned in the future, there will be some efforts in improving the webpack output

**Comment by kitsonk** [comment]
> Browser support for that method is good though:

Dojo 2 offers IE11 support out of the box.  Our examples should always show writing code that supports IE11.

> 1. Are we sure es6-string doesn't somehow polyfill startsWith automatically?

I am pretty sure since I wrote all the code... 😁 

> 2. As a general piece of feedback here, as a user, it's confusing what this message is, e.g. What is Dynamic features? Why is it telling me this? I think @matt-gadd mentioned in the future, there will be some efforts in improving the webpack output

Yes, we need to improve the output.  That is provided by [static optimization](https://github.com/dojo/webpack-contrib#static-build-loader) and is denoting that at build time you have statically asserted what features are available in your target environment, leaving them all to be dynamically determined at run-time.  You can optimise the build by supplying `--features` on the CLI and targeting specific environments.

**Comment by kitsonk** [comment]
Also, for posterity:

1. *polyfill* - functionality that is added to the runtime environment that appears on the surface to not be different from a native implementation.
2. *ponyfill* - the same functionality provided in a way that doesn't touch globals, so only those who expressly import the functionality have access to it.

The reason why we prefer ponyfills is that we have seen too many times _bad_ implementations of polyfills.  So for the functionality we maintain in `@dojo/shim` we always prefer to not pollute the global namespace with our functional fills.  For external polyfills (at the moment, those being PointerEvents and IntersectionObservers) we believe we use polyfills that are strongly aligned to the standard and we don't want the "burden" of re-implementing them.  The feature which we are rolling out via the static optimization though will allow those to be built out of the webpack bundles, but should result in a noop if the native feature is present.

For ECMAScript, we will probably always "own" those, as they are fundamental to the framework, and again, we prefer to provide them as ponyfills (importable modules).  To support `async`/`await` and downlevel emitting of iterators to ES5, TypeScript requires a global `Promise` and `Symbol` to be provided to allow the helpers to operate properly.  Therefore we expose those globally and they result in a noop if the native features are present.  The remaining functionality in `@dojo/shim` does not touch the global namespace and are modules that are importable and so only effect those that have an explicit dependency.

The static optimisation provide two main capabilities at build time, re-writing of `has(feature)` flags as static `true` or `false` values.  That causes something like this:

https://github.com/dojo/shim/blob/3a84308d7817ac5af0c435c7860f33fdb27a72d3/src/string.ts#L144-L154

To be written so that the values in the first line will be `true` or `false`.  When then webpack uses uglify to minify the code, uglify will perform dead code removal, leaving either the native or ponyfilled functionality in the bundle.  The other feature which we are in the process of rolling out is the ability to provide a pragma (`'has("foo")';`) which will then elide the next polyfill import, allowing an end developer to create a build that does not include certain polyfills it knows are not needed at run-time.

**Comment by umaar** [comment]
> When then webpack uses uglify to minify the code, uglify will perform dead code removal, leaving either the native or ponyfilled functionality in the bundle.

This is all pretty cool, wouldn't have known this happens out of the box (I mean as long as you supply `--features`) - will make a suggestion in the cookbook skeleton that we include this as a recipe!
