### ISSUE TITLE
Enable Continuous Deployment

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#56]
Configure the dojo.io site and project master branches to continuously deploy the site and API documentation

**Comment by devpaul** [comment]
Created PR #64 to handle continuous deployment of dojo.io site and allow a cron to build APIs nightly.

TODO

* add `deploy_key.enc` & register the deploy key w/ GitHub
* turn on continuous deployment of dojo packages's API docs on master
* add a nightly cron build to Travis
* set `DEPLOY_DOC` to publish when ready to enable continuous deployment

**Comment by devpaul** [comment]
I've added a number of PRs, enabled continuous deployment to the dojo.io site, and create and tested a cron on Travis to automatically build and publish the latest API documentation.

PRs:

* #80 Added a `grunt init` command to create an encrypted deployment key and register it w/ GH and Travis -- basically initialize automation
* #81 allow the presence of a HEXO_ROOT environment variable to change the hexo root so dojo.io can be deployed to forks (also created hexojs/hexo#2521 to fix a hexo bug blocking this feature)
* #82 updated the hexo task to create `site/source/api/index.md` based on the latest api documents
* #83 Added a deploy key using `grunt init`
* #84 Fixed an issue with `git` not able to lock the global `.git/config` due to a race condition
* #85 Fixed issues identifying the latest version of API docs

I think we should wait to turn on continuous deployment of dojo 2 API documents in their respective repositories. At this time we are not currently linking to these API documents from dojo.io; we are transitioning from building HTML files w/ TypeDoc to JSON; and, we have two different implementations of the API docs sync, build, and publish process that we should unify into a single implementation. It should be sufficient to continue building typedoc artifacts to validate they can be built and make changes later after we address the issues listed above.
